# Numpy

In [34]:
import numpy as np # Kütüphanenin import edilmesi

In [35]:
# liste = [1,2,3,4,5,6,7,8,9,10,11,12,13,14,15]
dizi = np.array([1,2,3,4,5,6,7,8,9,10,11,12,13,14,15]) # Array matematiksel operasyonların yapılmasını kolaylaştırır.
dizi

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15])

In [36]:
dizi.shape # Array boyutu gözlemlenir. 15x1'lik bir vektör.

(15,)

In [37]:
dizi2 = dizi.reshape(3,5) # 3x5 (3 satır, 5 sütundan oluşan)'lik bir matrise çevirilmiş hali.
dizi2

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15]])

In [38]:
print("Shape: ", dizi2.shape)
print("Dimension: ", dizi2.ndim)
print("Size: ", dizi2.size)
print("Type: ", type(dizi2))

Shape:  (3, 5)
Dimension:  2
Size:  15
Type:  <class 'numpy.ndarray'>


In [39]:
dizi2D = np.array(([1,2,3,4],[5,6,7,8],[9,8,7,6])) # 2 Boyutlu matrisin elle tanımı
dizi2D

array([[1, 2, 3, 4],
       [5, 6, 7, 8],
       [9, 8, 7, 6]])

In [40]:
sifir_dizi = np.zeros((3,4)) # 0'lardan oluşan 3x4'lük bir matris.
sifir_dizi 

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [41]:
bir_dizi = np.ones((3,4)) # 1'lerden oluşan 3x4'lük bir matris.
bir_dizi

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [42]:
bos_dizi = np.empty((2,4)) # 0'a çok yakın değerlerden oluşan 2x4'lük bir matris
bos_dizi

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [43]:
# arange(x,y,basamak) x'den başlar y'ye kadar basamak büyüklüğünde artarak ilerler.
dizi_aralik = np.arange(10,50,5)
dizi_aralik

array([10, 15, 20, 25, 30, 35, 40, 45])

In [44]:
# linspace (x,y,basamak) x'den başlar y'ye kadar(y dahil) basamak kadar sayıya bölerek ilerler.
dizi_bosluk = np.linspace(10,50,10)
dizi_bosluk

array([10.        , 14.44444444, 18.88888889, 23.33333333, 27.77777778,
       32.22222222, 36.66666667, 41.11111111, 45.55555556, 50.        ])

## Temel Operasyonlar

In [46]:
a = np.array([1,2,3])
b = np.array([4,5,6])

print("Toplama: ", a + b)
print("Çıkarma: ", a - b)
print("Dizinin karesi: ", a**2, b**2)

Toplama:  [5 7 9]
Çıkarma:  [-3 -3 -3]
Dizinin karesi:  [1 4 9] [16 25 36]


In [45]:
# Filtering - Filtreleme

c = np.array([0,1,2,3])
filtre = c < 2 # c array'nin içinde bulunan 2'den küçük değerleri gösterir.
c[filtre]

array([0, 1])

In [ ]:
d = np.array([[1,2,3], [4,5,6]]) # 2x3
e = np.array([[4,5,6], [1,2,3]]) # 2x3 -> T -> 3x2

print(d.dot(e.T)) # 2x2'lik bir matris çarpımı elde edilir.

print(sum(d))
print(np.sum(d)) # Matris toplamı gerçekleştirir.

print(d.sum(axis = 1)) # Satır toplamı yapar.
print(d.sum(axis = 0)) # Sütun toplamı yapar.

print("Max değer: ", np.max(d)) # Maximum değer gözlemlenir.
print("Min değer: ", np.min(d)) # Minimum değer gözlemlenir.

print(np.sqrt(d)) # Kök alma işlemi uygular.
print(np.square(d)) # Kare alma işlemi uygular.

In [47]:
rastgele_dizi = np.random.random((3,3)) # 3x3 boyutunda, 0 ile 1 arasında rastgele değerlerden oluşan bir dizi oluşturur.
rastgele_dizi

rastgele_norm_dizi = np.random.normal((0, 1, 100)) # 0 ortalama, 1 standart sapma ile 100 değer üreten normal dağılım
rastgele_norm_dizi

array([ -0.32891223,   0.79809624, 100.57182753])

## Indexing / Slicing - İndeksleme / Dilimleme

In [ ]:
dizi = np.array([1,2,3,4,5,6,7])

dizi[0] # Dizinin 0.indeksindeki değeri yazdırır.
dizi[0:3] # Dizinin 0.indeks (dahil) ve 3.indeks arasındaki değeri yazdırır.
dizi[:3] # Dizinin 0.indeks (dahil) ve 3.indeks arasındaki değeri yazdırır.

dizi[::-1] # Diziyi ters çevirir

In [ ]:
dizi2D = np.array([[1,2,3,4,5],[6,7,8,9,10]])
print(dizi2D)

dizi2D[0,0] # 0.Satır 0.Sütundaki değeri yazdırır.
dizi2D[1,2] # 1.Satır 2.Sütundaki değeri yazdırır.
dizi2D[1,:] # 1.Satırdaki tüm değerleri yazdırır.
dizi2D[:,2:4] # 0 ve 1. Satırdaki 2. ve 3. sütundaki değerleri dilimler ve yazdırır.

## Shape Manipulation - Şekil Manipülasyonu

In [ ]:
dizi2D = np.array([[1,2,3],[4,5,6],[7,8,9]])

dizi2D_shape = dizi2D.shape # Dizi2D değişkenimizin boyut değerini farklı bir değişkene tekrardan kullanmak için atadık.

dizi2D.reshape(dizi2D_shape[0]*dizi2D_shape[1],1) # 9x1'lik bir vektöre çevirdik.
# Bir matristeki tüm elemanları tek bir sütun olarak almak, genellikle işlem kolaylığı sağlar.

dizi2D.ravel() # Tensorflow --> flatten. Üstteki kodla aynı işlemi yapar.

dizi2D.T # Transpose alma işlemi bu şekilde yapılır.

In [ ]:
"""
Ders İçi Ödev
1-) A array = 2 boyutlu bir tane array -> (3,5)
2-) B array = 1 boyutlu bir tane array -> (15,)
3-) B array'ini (3,5) olacak şekilde reshape yapalım.
4-) C = A + B
5-) D=linspace ve E=arange ile (3,5) lik matrisler oluşturalım
6-) F = D + E
7-) C'nin ve F'nin her bir elemanını for döngüsü ile eleman eleman çarpıp G = (15,1)
8-) C ve F'yi (15,1) sonrasında C'nin ilk elemanı ile F'nin son elemanı toplayarak ilerleyelim.
9-) Toplam değerleri 1'den büyükse G1 isimli bir listeye, küçükse G2'ye atayalım.
"""

# 1-)
A = np.array([[1,2,3,4,5],[6,7,8,9,10],[11,12,13,14,15]])

print(A)
print("Boyut Sayısı: ", A.ndim)
print("Boyut: ", A.shape)

# 2-)
B = np.array(np.arange(15))

print(B)
print("Boyut Sayısı: ", B.ndim)
print("Boyut: ", B.shape)

# 3-)
B_reshaped = B.reshape(3,5)
print("Boyut: ", B_reshaped.shape)

# 4-)
C = A + B_reshaped
print("C Dizisi (A + B):")
print(C)

# 5-)
D = np.linspace(0, 14, 15).reshape(3, 5)  # 0 ile 14 arasında 15 sayıyı eşit aralıklarla oluşturup 3x5 matris haline getiriyoruz
print("D (linspace ile oluşturulmuş matris):")
print(D)

E = np.arange(15).reshape(3, 5)  # 0 ile 14 arasındaki sayıları arange ile oluşturup 3x5 matris haline getiriyoruz
print("E (arange ile oluşturulmuş matris):")
print(E)

# 6-)
F = D + E
print("F Dizisi (D + E):")
print(F)

# 7-)
G = np.zeros((15, 1))  # G dizisini (15, 1) boyutunda sıfırlarla başlatıyoruz
index = 0  # C ve F dizilerinin elemanlarını sırasıyla çarpmak için bir index

for i in range(C.shape[0]):  # Satırlar üzerinden dönecek
    for j in range(C.shape[1]):  # Sütunlar üzerinden dönecek
        G[index] = C[i, j] * F[i, j]  # Elemanları çarpıyoruz
        index += 1  # Bir sonraki index'e geçiyoruz

print("G Dizisi (C ve F'nin elemanlarının çarpımı):")
print(G)

# 8 ve 9-)
C_reshaped = C.reshape(15,1)
F_reshaped = F.reshape(15,1)

G1 = []  # Toplamları 1'den büyük olanlar
G2 = []  # Toplamları 1'den küçük veya eşit olanlar

for i in range(len(C_reshaped)):
    toplam = C_reshaped[i, 0] + F_reshaped[-(i + 1), 0]  # İlk eleman ile son eleman, sırayla toplama
    if toplam > 1:
        G1.append(toplam)
    else:
        G2.append(toplam)

print(G1, G2)